language: cpp
compiler: g++

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode8.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -qq update ; fi

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - build-essential
    - libgtk-3-dev
    - libgtkmm-3.0-dev

script:
  - cmake .
  - make

cache:
    apt: true

notifications:
  email: false
