language: cpp
compiler: g++

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo add-apt-repository -y ppa:andrew-fuller/cmake && sudo apt-get -qq update ; fi

addons:
  apt:
    sources:
    - sourceline: 'ppa:andrew-fuller/cmake'
    packages:
    - cmake
    - build-essential
    - gcc
    - g++
    - libgtk-3-dev
    - libgtkmm-3.0-dev
  homebrew:
    packages:
    - gtk+3
    - gtkmm3
    - cmake
    update: true

script:
  - cmake .
  - make

cache:
    apt: true

notifications:
  email: false
