# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


stages:
  - stage: Tutti
    jobs:
    - job: Tutti1
      strategy:
        matrix:
          Linux:
            osName: 'Linux'
            imageName: 'ubuntu-18.04'
          Mac:
            osName: 'Mac'
            imageName: 'macos-10.15'
      pool:
        vmImage: $(imageName)
      steps:
      - bash: sudo apt remove -y cmake && sudo add-apt-repository -y ppa:andrew-fuller/cmake && sudo apt-get update && sudo apt install -y cmake make build-essential g++ gcc libgtk-3-dev libgtkmm-3.0-dev
        displayName: Install Dependencies Linux
        condition: eq( variables['Agent.OS'], 'Linux' )
      - bash: brew install gtk+3 gtkmm3 cmake
        displayName: Install Dependencies macOS
        condition: eq( variables['Agent.OS'], 'Darwin' )
      - bash: mkdir build && cd build && which cmake && dpkg -L cmake && cmake --version && cmake .. && make
        displayName: Build
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/build/tasarch'
          artifact: 'TASArch'
          publishLocation: 'pipeline'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/cores/'
          artifact: 'cores'
          publishLocation: 'pipeline'
