# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


stages:
  - stage: Build_All
    jobs:
    - job: BuildAll
      strategy:
        matrix:
          Linux:
            osName: 'Linux'
            imageName: 'ubuntu-18.04'
          Mac:
            osName: 'Mac'
            imageName: 'macos-10.14'
      pool:
        vmImage: $(imageName)
      steps:
      - checkout: self
        submodules: recursive
      - bash: sudo bash -c 'echo "deb http://archive.ubuntu.com/ubuntu/ disco main restricted" >> /etc/apt/sources.list' && export DEBIAN_FRONTEND=noninteractive && export UCF_FORCE_CONFOLD=1 && sudo -E apt-get update && sudo -E apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y cmake libgtk-3-dev libgtkmm-3.0-dev libarchive-dev
        displayName: Install Dependencies Linux
        condition: eq( variables['Agent.OS'], 'Linux' )
      - bash: brew install gtk+3 gtkmm3 cmake pkg-config libarchive
        displayName: Install Dependencies macOS
        condition: eq( variables['Agent.OS'], 'Darwin' )
      - bash: ./build_release.sh
        displayName: Build
      - task: PublishPipelineArtifact@1
        displayName: Publish Release
        inputs:
          targetPath: '$(Build.SourcesDirectory)/build/tasarch-$(Agent.OS)-$(Build.Id)'
          artifact: 'tasarch-$(Agent.OS)-$(Build.Id)'
          publishLocation: 'pipeline'