# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


stages:
  - stage: Build
    jobs:
    - job: Backend
      strategy:
        matrix:
          Linux:
            osName: 'Linux'
            imageName: 'ubuntu-18.04'
      pool:
        vmImage: $(imageName)
      steps:
      - bash: sudo add-apt-repository -y ppa:andrew-fuller/cmake && sudo apt-get -qq update && sudo apt install -y cmake make build-essential g++ gcc libgtk-3-dev libgtkmm-3.0-dev
      - bash: mkdir build && cd build && cmake --version && cmake .. && make
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/build/tasarch'
          artifact: 'TASArch'
          publishLocation: 'pipeline'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/cores/'
          artifact: 'cores'
          publishLocation: 'pipeline'
